# Generated by Django 3.0.7 on 2020-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_parsing_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_site', models.CharField(max_length=50)),
                ('id_book', models.TextField()),
                ('book_url', models.TextField()),
                ('parsing', models.TextField()),
            ],
            options={
                'db_table': 'book_parsing_list',
            },
        ),
        migrations.CreateModel(
            name='book_parsing_site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_site', models.TextField()),
            ],
            options={
                'db_table': 'book_parsing_site',
            },
        ),
        migrations.CreateModel(
            name='book_plugins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plugins_file', models.TextField()),
                ('plugins_name', models.TextField()),
                ('plugins_name_ru', models.TextField()),
                ('plugins_site_parsing', models.TextField()),
                ('plugins_date', models.TextField()),
                ('plugins_create', models.TextField()),
            ],
            options={
                'db_table': 'book_plugins',
            },
        ),
        migrations.CreateModel(
            name='book_session',
            fields=[
                ('id_sess', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=50)),
                ('code_sess', models.TextField()),
                ('user_agent_sess', models.TextField()),
                ('date_sess', models.DateTimeField()),
                ('used_sess', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_session',
            },
        ),
        migrations.CreateModel(
            name='book_union',
            fields=[
                ('id_union', models.AutoField(primary_key=True, serialize=False)),
                ('title_union', models.TextField()),
                ('id_books', models.TextField()),
            ],
            options={
                'db_table': 'book_union',
            },
        ),
        migrations.CreateModel(
            name='book_update_parsing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count_book_mark', models.CharField(max_length=50)),
                ('all_stage', models.CharField(max_length=50)),
                ('curent_stage', models.CharField(max_length=50)),
                ('time', models.TextField()),
            ],
            options={
                'db_table': 'book_update_parsing',
            },
        ),
        migrations.CreateModel(
            name='book_users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login_user', models.TextField()),
                ('passwd_user', models.TextField()),
                ('mail_user', models.TextField()),
                ('sex_user', models.CharField(max_length=50)),
                ('key_user', models.TextField()),
                ('acces', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_users',
            },
        ),
        migrations.CreateModel(
            name='book_users_config',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('type_get', models.TextField()),
                ('update_time', models.TextField()),
                ('song', models.TextField()),
                ('theme_id', models.CharField(max_length=50)),
                ('show_custom', models.TextField()),
                ('redirect_read', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_users_config',
            },
        ),
    ]
