# Generated by Django 3.0.7 on 2020-06-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_custom_mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.TextField()),
                ('url_mark', models.TextField()),
                ('mark', models.TextField()),
                ('id_user', models.CharField(max_length=50)),
                ('id_status', models.CharField(max_length=50)),
                ('comment', models.DateTimeField()),
            ],
            options={
                'db_table': 'book_custom_mark',
            },
        ),
        migrations.CreateModel(
            name='book_mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_site', models.CharField(max_length=50)),
                ('id_books', models.CharField(max_length=50)),
                ('id_chapters', models.CharField(max_length=50)),
                ('id_user', models.CharField(max_length=50)),
                ('id_status', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_mark',
            },
        ),
        migrations.CreateModel(
            name='book_status_mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_satus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_status_mark',
            },
        ),
    ]
