# Generated by Django 3.0.7 on 2020-06-25 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_library',
            name='id_site',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_mark',
            name='date_update',
            field=models.TextField(),
        ),
    ]
