# Generated by Django 3.0.7 on 2020-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_chapters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_site', models.CharField(max_length=50)),
                ('id_book', models.CharField(max_length=50)),
                ('id_chapter', models.CharField(max_length=50)),
                ('title_chapter', models.TextField()),
                ('url_chapter', models.TextField()),
                ('pay_chapter', models.TextField()),
            ],
            options={
                'db_table': 'book_chapters',
            },
        ),
    ]
